sudo: required
dist: trusty
language: c

before_install:
    # update package list
    - sudo apt-get update -qq

install:
    # install packages needed for mk-build-deps
    - sudo apt-get install -qq --no-install-recommends devscripts equivs shellcheck
    # pull build deps from debian/control
    - sudo mk-build-deps -ir -t "apt-get --yes --no-install-recommends"
    # remove packages needed for mk-build-deps
    - sudo apt-get purge -qq equivs
    - sudo apt-get autoremove -qq

script:
    # build the debian package
    - dpkg-buildpackage -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc

env:
  global:
    # travis encrypt -r waja/config-apt-update GITHUBTOKEN=XXXXXX (https://help.github.com/articles/creating-an-access-token-for-command-line-use / http://docs.travis-ci.com/user/encryption-keys/)
    secure: "PQR97romW+p0eGU64FgO+NhwOHp97/ozoDgxOQTc+T4VndnBg6rpUH8Apq4sRCjpt6UOOLyus1cQt6PvKiD6t6Y1fPCWMVwZZbT9kVpWxNcq8A3QPlx2cX0HvyOgc5EwLqIgQgQtuL2eltEZvPsYUU/AS7QZuHston6uVTSaqAg="

after_success:
    - mkdir -p debian/build/release/
    - for FILE in $(dcmd ../*.changes); do cp ../$(basename $FILE) debian/build/release/; done
    - debian/bin/github-release.sh "$TRAVIS_REPO_SLUG" "debian/`head -1 debian/changelog | awk -F'[()]' '{print $2}' | awk -F'+' '{print $1}'`" debian/build/release/*

#notifications:
#  email: false
