#!/bin/sh
HASHFILE="/var/lib/config-apt-update/hostname.hash"
HASHMECH=`which sha512sum`
if [ $? -ne 0 ]; then
        HASHMECH=`which sha1sum`
fi

if [ -f /etc/default/config-apt-update ]
then
	. /etc/default/config-apt-update
	if [ -z "$EMAIL" ]
	then
		printf "#### WARNING ####\n"
		printf "EMAIL in /etc/default/config-apt-update not set!\n"
		printf "#################\n"
	        exit 0
	fi
else
	printf "#### WARNING ####\n"
	printf "/etc/default/config-apt-update is missing!\n"
	printf "#################\n"
	exit 0
fi

if [ -f ${HASHFILE} ]
then
	. ${HASHFILE}
fi

TMPMAIL="`mktemp`"
# get hostname from address
getaddress()
{
	if [ ! ${ADDRESS} ]
	then
		if [ ! ${IFACE} ]
		then
			IFACE="`/sbin/route -n | grep ^0.0.0.0 | awk ' { print $8 }'`"
		fi
		IP="`LC_ALL=en /sbin/ifconfig ${IFACE} | sed -n -e'/inet addr:/s/^.*inet addr:\([0-9.]*\).*$/\1/p'`"
		if [ -x /usr/bin/drill ]
		then
			if [ -n `/usr/bin/drill -x ${IP} | grep -v "^;;" | grep PTR | awk '{print $5}'` ]
				then
				ADDRESS="`/usr/bin/drill -x ${IP} | grep -v "^;;" | grep PTR | awk '{print $5}'`"
			fi
		elif [ -x /usr/bin/host ]
		then
			if [ `LC_ALL=en /usr/bin/host ${IP} | tail -1 | awk ' { print $3 }'` != not ]
				then
				ADDRESS="`LC_ALL=en /usr/bin/host ${IP} | tail -1 | awk ' { print $5 }'`"
			fi
		else
			ADDRESS="${IP}"
		fi

		if [ -z "${ADDRESS}" ]
		then
			ADDRESS="`/bin/hostname -f`"
		fi
	fi
}

# get new packages list
apt-get update > /dev/null

# remove leading and trailing whitespaces from value
EXCLUDE="`echo ${EXCLUDE} | sed 's/^[ \t]*//;s/[ \t]*$//'`"

if [ -z "${EXCLUDE}" ]
then
	if [ "`apt-get --just-print -u upgrade | grep '^Inst ' | awk ' { print $2 }' | wc -l`" -gt "0" ]
	then
		getaddress
		printf "apt-get upgrade would like to install these packages:\n\n" > "${TMPMAIL}"
		apt-get --just-print -u upgrade | grep '^Inst ' | awk ' { print $2"\t"$3"\t"$4")" } ' >> "${TMPMAIL}"
		${MAIL} ${EMAIL} -s "Updates available on ${ADDRESS}" < "${TMPMAIL}"
		rm -f "${TMPMAIL}"
	fi
else
	if [ "`apt-get --just-print -u upgrade | grep '^Inst ' | grep -v -E "${EXCLUDE}" | awk ' { print $2 }' | wc -l`" -gt "0" ]
	then
		getaddress
		printf "apt-get upgrade would like to install these packages:\n\n" > "${TMPMAIL}"
		apt-get --just-print -u upgrade | grep '^Inst ' | grep -v -E "${EXCLUDE}" | awk ' { print $2"\t"$3"\t"$4")" } ' >> "${TMPMAIL}"
		${MAIL} ${EMAIL} -s "Updates available on ${ADDRESS}" < "${TMPMAIL}"
		rm -f "${TMPMAIL}"
	fi
fi
